name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --locked

      - name: Check code style (Ruff)
        run: uv run ruff check --output-format=github

  tests-locked:
    name: Run tests with locked dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests (pytest)
        run: uv run pytest

  build-package:
    name: Build package
    needs: [quality, tests-locked]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v5

      - name: Build package
        run: uv build

      - name: Verify package
        run: ls -l dist/
